global:
  resolve_timeout: 5m

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "web.hook"
  routes:
  - receiver: "web.hook"
    group_by: ["service"]
    match_re:
      alertname: "Server.*Down"
receivers:
- name: "web.hook"
  webhook_configs:
    - url: "http://127.0.0.1:5001/"
inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "dev", "instance"]
  - source_match_re:
      alertname: "Server.*Down"
    target_match:
      alertname: "DownStreamServiceDown"